### ISSUE TITLE
Animation Not working as expected

### ISSUE THREAD

**Issue by wouzer** [custom-cards/canvas-gauge-card#36] opened 2020-06-29 14:42 UTC
Animation of gauge not working as expected. It doesn't animate from the old value to the new, but 0 to the new. According to the description of the canvas-gauges (https://canvas-gauges.com/documentation/user-guide/configuration), it should animate the needle from old to new value.

Here is my (lovelace) config of the card:

card_height: 175
entity: sensor.verbruik_current
gauge:
  animation: true
  animationDuration: 1500
  animationRule: linear
  borderInnerWidth: 0
  borderMiddleWidth: 0
  borderOuterWidth: 0
  borderShadowWidth: 0
  borders: false
  height: 175
  highlights:
    - color: 'rgba(200, 50, 50, .75)'
      from: 4000
      to: 5000
  majorTicks:
    - '0'
    - ' '
    - '1000'
    - ' '
    - '2000'
    - ' '
    - '3000'
    - ' '
    - '4000'
    - ' '
    - '5000'
  maxValue: 5000
  minValue: 0
  minorTicks: 5
  startAngle: 45
  strokeTicks: false
  ticksAngle: 270
  title: Verbruik (W)
  type: radial-gauge
  valueBox: true
  valueDec: 0
  width: 200
type: 'custom:canvas-gauge-card'

**Comment by dhover** [comment] 2020-08-20 09:13
Same issue here!

**Comment by Olen** [comment] 2020-11-19 13:37
That is probably caused by this upstream issue:
https://github.com/Mikhus/canvas-gauges/issues/106
Which should be fixed there.  
Probably just need to update the dependencies of this card to be canvas-gauges 2.1.7, but I have not tested it, so I don't know if that breaks something else...

**Comment by eBoon123** [comment] 2021-03-08 18:23
> Animation of gauge not working as expected. It doesn't animate from the old value to the new, but 0 to the new. According to the description of the canvas-gauges (https://canvas-gauges.com/documentation/user-guide/configuration), it should animate the needle from old to new value.
> 
> Here is my (lovelace) config of the card:
> 
> card_height: 175
> entity: sensor.verbruik_current
> gauge:
> animation: true
> animationDuration: 1500
> animationRule: linear
> borderInnerWidth: 0
> borderMiddleWidth: 0
> borderOuterWidth: 0
> borderShadowWidth: 0
> borders: false
> height: 175
> highlights:
> - color: 'rgba(200, 50, 50, .75)'
> from: 4000
> to: 5000
> majorTicks:
> - '0'
> - ' '
> - '1000'
> - ' '
> - '2000'
> - ' '
> - '3000'
> - ' '
> - '4000'
> - ' '
> - '5000'
> maxValue: 5000
> minValue: 0
> minorTicks: 5
> startAngle: 45
> strokeTicks: false
> ticksAngle: 270
> title: Verbruik (W)
> type: radial-gauge
> valueBox: true
> valueDec: 0
> width: 200
> type: 'custom:canvas-gauge-card'

I'm seeing the same thing. Just installed 0.4.1. Had to turn _**animation**_ to False to avoid the annoying flickering back t0 0 on every update. These gauges are very cool though - thanks for making this available to Home Assistant!!!

**Comment by cooperised** [comment] 2021-04-21 15:00
Same issue here, not that it needs much confirmation at this point.  It would be great to know the cause!

**Comment by kaijk** [comment] 2022-01-27 00:19
At least I can stop chasing this in my configuration.  I'd love a fix as well.
Thanks!

**Comment by lloyda** [comment] 2022-06-14 11:11
Would also love to see a fix for this.

**Comment by wuast94** [comment] 2022-12-16 18:57
any uptade to this?

**Comment by seganku** [comment] 2023-01-21 16:27
`animation: false` helps a lot, but it would be great to be able to keep animation without the constant jump to zero.

**Comment by rhadamantys** [comment] 2023-02-14 20:31
I did some debugging recently, and I figured, that the gauge card gets initialized every time, a new value is added. That means, that the current value (the value, that the needle shows) is reset to zero and thus, the animation always starts at zero. I tried to add some additional members and store values, they all get reset as well. So my guess is, that the embedding of the gauge in home assistant causes the trouble. The gauge itself is working fine.

**Comment by rhadamantys** [comment] 2023-03-21 13:18
One question: how do you "compile" all the lib/*.js files into one custom card "canvas-gauge-card.js"?

**Comment by rhadamantys** [comment] 2023-03-21 19:04
@Olen: you were right. It is actually `if (this._gauge == null) { }` in the canvas-gauge-card.ts file. Now it is working locally on my home assistant instance. Thanks a lot for the suggestion!

**Comment by helto4real** [comment] 2023-03-31 10:39
Should be fixed in version 0,7 
https://github.com/custom-cards/canvas-gauge-card/releases/tag/0.7

**Closed by helto4real** 2023-03-31 10:39 UTC

**Comment by Habile2019** [comment] 2023-04-02 15:45
Thank you for this! I'm not sure the JS made it into the release though? I don't see the changes after updating.

**Comment by reisfni** [comment] 2023-04-06 23:11
> Thank you for this! I'm not sure the JS made it into the release though? I don't see the changes after updating.
+1
